apiVersion: v1
kind: Service
metadata:
  labels:
    name: test-metrics
  name: test-metrics
  namespace: dh-prod-monitoring
spec:
  ports:
  - name: test-metrics
    port: 443
    protocol: TCP
    targetPort: 8000
  selector:
    app: test-metrics
  sessionAffinity: None
  type: ClusterIP
